spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaitunc/pdb-config-repo.git
          repos:
            local:
                pattern: 
                    - '*/local'
                uri: file:///C:/workspaces_pdb/pdb-config-repo   


security:
  user:
    password: ${config_server_secret}