spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo
        
  profiles:
     active: local

server:
  port: 8888

security:
  user:
    password: test