spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaitunc/pdb-config-repo.git
        
  profiles:
     active: local


security:
  user:
    password: ${config_server_secret}
